[workspace]
git_only = true
publish = false
release_always = false
release_commits = "^(feat|fix|perf|refactor|revert|security)[(:]"
git_tag_name = "v{{ version }}"
pr_name = "chore(release): release v{{ version }}"
semver_check = false
